---
- name: Base setup for AWS infra
  hosts: dci_ng
  gather_facts: true
  become: true

  roles:
    - name: infra.simple
      tags:
        - base

    - name: infra.node_exporter
      tags:
        - base
        - node_exporter

    - name: infra.quadlet
      tags:
        - base
        - podman

    - name: quadlet.podman_exporter
      tags:
        - base
        - podman

- name: Setup monitoring stack
  hosts: dci_prometheus:&dci_ng
  gather_facts: true
  become: true

  roles:
    - name: quadlet.prometheus
      tags:
        - podman
        - prometheus
        - monitoring

    - name: quadlet.alertmanager
      tags:
        - podman
        - alertmanager
        - monitoring

    - name: quadlet.grafana
      tags:
        - podman
        - grafana
        - monitoring

    - name: quadlet.blackbox_exporter
      tags:
        - podman
        - monitoring

    - name: quadlet.domain_exporter
      tags:
        - podman
        - monitoring

    - name: quadlet.nginx
      tags:
        - podman
        - nginx
        - monitoring

- name: Setup haproxy
  hosts: dci_api:dci_doc:dci_ui:&dci_ng
  gather_facts: true
  become: true

  roles:
    - name: quadlet.haproxy
      tags:
        - haproxy
        - podman

- name: Setup DCI-API
  hosts: dci_api:&dci_ng
  gather_facts: true
  become: true

  roles:
    - name: quadlet.dci_api
      tags:
        - dci_api
        - podman

- name: Setup DCI-DOC
  hosts: dci_doc:&dci_ng
  gather_facts: true
  become: true

  roles:
    - name: quadlet.dci_doc
      tags:
        - dci_doc
        - podman

- name: Setup DCI-UI
  hosts: dci_ui:&dci_ng
  gather_facts: true
  become: true

  roles:
    - name: quadlet.dci_ui
      tags:
        - dci_ui
        - podman

- name: Setup haproxy DCI frontend
  hosts: dci_api:dci_doc:dci_ui:&dci_ng
  gather_facts: true
  become: true

  tasks:
    - ansible.builtin.import_role:
        name: quadlet.haproxy
        tasks_from: frontend_dci
      tags:
        - haproxy
        - podman
